name: Backend

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    name: Testing
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:4.3.6-community
        env:
          NEO4J_dbms_connector_bolt_enabled: "true"
          NEO4J_dbms_security_auth__enabled: "false"
        options: >-
          --health-cmd "cypher-shell 'match (n) return count(n)'" 
          --health-timeout 30s
          --health-retries 20
          --health-interval 30s
          --health-start-period 30s
        ports:
          - 7687:7687

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install dependencies
        id: install_dependencies
        working-directory: ${{ github.workspace }}
        run: pip3 install -r packages.txt

      - name: Initialize database
        id: initialize_db
        working-directory: ${{ github.workspace }}/db
        run: |
          ${{ github.workspace }}/db/scripts/ci/make_config.sh config.ini
          ./scripts/run_bootstrap.sh

      - name: Run service
        id: run_tests
        working-directory: ${{ github.workspace }}/web/backend
        env:
          CONFIG_PATH_TO_SC_CONFIG: db.ini
          CONFIG_NEO4J_PASS: ${{ secrets.NEO4J_PASSWORD }}
        run: |
          ${{ github.workspace }}/db/scripts/ci/make_config.sh db.ini
          ./scripts/ci/make_config.sh service.ini
          ./scripts/ci/run_tests.sh service.ini